name: Build IPC

# This workflow is triggered from the main CI workflow.
on:
  workflow_call:

jobs:
  build:
    name: Build IPC
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
      RUSTFLAGS: -Dwarnings

    steps:
      # https://github.com/marketplace/actions/free-disk-space-ubuntu
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
          swap-storage: false
          docker-images: false
          android: true
          dotnet: true
          haskell: true

      - name: Check out the project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Tools
        uses: ./.github/actions/install-tools
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          rust: stable

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.19.0

      - name: Cache Cargo Build
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.cargo/registry
            /home/runner/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Solidity ABI artifacts
        uses: actions/cache@v2
        with:
          path: ./contracts/out
          key: contracts-abi-${{ hashFiles('./contracts/src/**/*.sol') }}

      - name: Check fmt (fmt, clippy)
        run: cargo fmt --check --all

      - name: Check clippy
        run: cargo clippy --tests --no-deps -- -D clippy::all

      - name: Build all
        run: |
          cd fendermint && make $PWD/builtin-actors/output/bundle.car
          cargo build --locked --release

      - name: Build Docker image for e2e tests
        run: |
          cat <<EOF > /tmp/Dockerfile
          FROM alpine as builder

          COPY /fendermint/app/config /app/fendermint/app/config
          COPY /target/release/fendermint /app/output/bin/fendermint
          COPY /target/release/ipc-cli /app/output/bin/ipc-cli
          
          EOF
          
          cat fendermint/docker/runner.Dockerfile >> /tmp/Dockerfile
          
          DOCKER_BUILDKIT=1 docker build \
            --load \
            -f /tmp/Dockerfile \
            -t fendermint:latest $(PWD)

      - name: Export Docker image
        run: docker save fendermint:latest > /artifacts/image.tar

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: /artifacts
