name: Fendermint CI - Test

# This workflow is triggered from the main CI workflow.
on:
  workflow_call:

env:
  CARGO_INCREMENTAL: '0'
  SCCACHE_CACHE_SIZE: 10G
  CC: "sccache clang"
  CXX: "sccache clang++"
  PROFILE: "ci"
  BUILDX_FLAGS: "--cache-from=type=gha --cache-to=type=gha,mode=max"

jobs:
  # Check code formatting; anything that doesn't require compilation.
  pre-compile-checks:
    # Skip tests on draft PRs, they take a long time, and drafts are for visibility.
    if: ${{ !github.event.pull_request.draft }}

    name: Build IPC Fendermint Image
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
      RUSTFLAGS: -Dwarnings

    steps:
      # https://github.com/marketplace/actions/free-disk-space-ubuntu
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
          swap-storage: false
          docker-images: false
          android: true
          dotnet: true
          haskell: true

      - name: Check out the project
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Tools
        uses: ./.github/actions/install-tools
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          rust: stable

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.19.0

      - name: Cache Cargo Build
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.cargo/registry
            /home/runner/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Solidity ABI artifacts
        uses: actions/cache@v2
        with:
          path: ./contracts/out
          key: contracts-abi-${{ hashFiles('./contracts/src/**/*.sol') }}

      - name: Generate Solidity ABI artifacts
        run: >-
          [ -d contracts/out ] || (cd contracts && curl -L https://foundry.paradigm.xyz | bash && export PATH="$PATH:/home/runner/.config/.foundry/bin" && foundryup && make compile-abi)

      - name: Compile Binding
        env:
          PROMTAIL_CLIENT_URL: ${{ secrets.PROMTAIL_CLIENT_URL }}
        run: cd contracts && make rust-binding

      - name: Format
        env:
          PROMTAIL_CLIENT_URL: ${{ secrets.PROMTAIL_CLIENT_URL }}
        run: cargo fmt --all --check

      - name: Clippy
        env:
          PROMTAIL_CLIENT_URL: ${{ secrets.PROMTAIL_CLIENT_URL }}
        run: cargo clippy --all

      - name: Unit Tests
        env:
          PROMTAIL_CLIENT_URL: ${{ secrets.PROMTAIL_CLIENT_URL }}
        run: cd fendermint && make build test

      - name: Inject Rust Cache Into Docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "/home/runner/.cargo/registry": "/root/.cargo/registry",
              "/home/runner/.cargo/git": "/root/.cargo/git"
              "target": "/app/target"
            }

      - name: Build Fendermint Docker Image
        env:
          PROMTAIL_CLIENT_URL: ${{ secrets.PROMTAIL_CLIENT_URL }}
        run: cd fendermint && make docker-build

      - name: Export
        run: docker save fendermint:latest > /tmp/fendermint.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fendermint
          path: /tmp/fendermint.tar
