name: Fendermint CI - Test

# This workflow is triggered from the main CI workflow.
on:
  workflow_call:

env:
  CARGO_INCREMENTAL: '0'
  SCCACHE_CACHE_SIZE: 10G
  CC: "sccache clang"
  CXX: "sccache clang++"
  PROFILE: "ci"
  BUILDX_FLAGS: "--cache-from=type=gha --cache-to=type=gha,mode=max"

jobs:
  tests:
    # Skip tests on draft PRs, they take a long time, and drafts are for visibility.
    if: ${{ !github.event.pull_request.draft }}

    name: Fendermint E2E Tests
    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: full
      RUSTFLAGS: -Dwarnings

    steps:
      - name: Checkout Fendermint
        uses: actions/checkout@v2
        with:
          repository: 'consensus-shipyard/ipc'
          submodules: 'recursive'
          path: 'ipc'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install cargo-make
        run: |
          if ! command -v cargo-make &> /dev/null
          then
              cargo install -f cargo-make
          fi

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fendermint
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/fendermint.tar
          docker image ls -a

      - name: Run Test
        run: cd fendermint && make e2e-only

