name: Run tests against Fendermint (remote Docker image)

# This workflow is triggered from the main CI workflow.
on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: full
      RUSTFLAGS: -Dwarnings

    steps:
      - name: Check out the project
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache Solidity ABI artifacts
        uses: actions/cache@v2
        with:
          path: ./contracts/out
          key: contracts-abi-${{ hashFiles('./contracts/**/*.sol') }}

      - name: Cache Cargo Build
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.cargo/registry
            /home/runner/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run unit tests
        run: make test-rust

